### ISSUE TITLE
ds.dim does not check for string

### ISSUE THREAD

**Issue by fdlk** [datashield/dsBaseClient#239]
When I execute `ds.dim(D)`, instead of `ds.dim("D")`, datashield4j gets upset:

```
"Bad request: Error parsing expression 'dimDS(function (expr, name) \n.External(C_doD, expr, name))': Lexical error at line 2, column 2.  Encountered: \"E\" (69), after : \".\""
```

I would expect that dsBaseClient does not send requests that datashield4j forbids.

**Comment by StuartWheater** [comment]
I take it you mean ds.dim("D"). I will investigate. Please could you look at the contents of the R Server' log files "/var/lib/rserver/logs/" and Opal's log files in "/var/log/opal/", and let us know if there is any indication of the underlying cause.
Stuart

**Comment by fdlk** [comment]
> I take it you mean ds.dim("D")
Whoops! That's what I should've typed, yes.
I think my issue then is that dsBaseClient doesn't warn me that I should provide a string.

**Comment by StuartWheater** [comment]
Thanks. It is clear we need to provide a clearer/better error message.
Stuart

**Comment by fdlk** [comment]
I have updated the description. Thanks for the quick response!

**Comment by StuartWheater** [comment]
By the way, D being a function in stats package made the error message even more misleading.
Stuart
