### ISSUE TITLE
First version of coxphSLMA

### ISSUE THREAD

**Issue by tombisho** [datashield/dsBaseClient#264]
This is a placeholder for the work that is being done for study level meta analysis of Cox proportional hazards models fitted at each cohort.

The work is requested by the InterConnect project and will likely be used in other projects such as LifeCycle.

More detail will be provided after some design discussions. The intention is that the first release of these functions will offer functionality equivalent to what is possible in DataSHIELD today (piecewise Poisson regression), but much easier to use and more familiar to analysts.

**Comment by StuartWheater** [comment]
Would you like this in v6.1 or wait for v6.2?

**Comment by tombisho** [comment]
If it's ok, we need to flesh out what is needed to get to a 'minimum viable product' and then we might know how long it might take to do... if I'm honest we are also a little unsure about when v6.1 and v6.2 are targeted. Is v6.1 the end of the year or sooner?

**Comment by davraam** [comment]
The coxphSLMA function is now included in the dsSurvival package

**Comment by neelsoumya** [comment]
https://github.com/neelsoumya/dsSurvival
