### ISSUE TITLE
Integrate an enhanced R parser

### ISSUE THREAD

**Issue by StuartWheater** [datashield/dsBaseClient#265]
Recode to take advantage of an enhanced R parser, within Opal, which permits passing of more complicated R formula.

**Comment by ymarcon** [comment]
Is this R parser already deployed in Opal?

**Comment by StuartWheater** [comment]
The enhancements to the R Parser are being developed at the moment, and plan to make a Pull Request to datashield4j as usual. This enhancement is for changes to the dsBaseClient code to remove current "workaround" to R Parser restrictions on formulas.

**Comment by StuartWheater** [comment]
R Parser is now configurable
