### ISSUE TITLE
Output from assign functions

### ISSUE THREAD

**Issue by andrewjamesturner0** [datashield/dsBaseClient#3]
## Feature request

Assign functions should output the name of any newly created objects.
### Current behaviour

```
> ds.log('D$LAB_HDL')
> ds.exists('LAB_HDL_log')
$study1
[1] TRUE
>
```
### Improvement

```
> ds.log('D$LAB_HDL')
$study1
New object created: LAB_HDL_log
>
```

**Comment by andrewjamesturner0** [comment]
### Further improvement

Add output showing the length of the new variable on each study. For example:

    > ds.log('D$LAB_HDL')
    $study1
    New object created: LAB_HDL_log
    Length:                     3000
    >

**Comment by pb51** [comment]
This functionality now implicit to all assign functions
