### ISSUE TITLE
ds.cbind not always checks properly the assignation of colnames + unused argument

### ISSUE THREAD

**Issue by ESCRI11** [datashield/dsBaseClient#330]
https://github.com/datashield/dsBaseClient/blob/d33615d7c9d41b47f2ee7f6d597ca62fcf721934/R/ds.cbind.R#L178

The aforementioned line may yield to unexpected behaviour, as an example:

We may have a table with the following class:

`data("CO2")`
`class(CO2)`
`[1] "nfnGroupedData" "nfGroupedData"  "groupedData"    "data.frame"`

Which is indeed a data.frame, however, if we do:

`class(CO2) %in% c('data.frame', 'matrix')`

We obtain:

`[1] FALSE FALSE FALSE  TRUE`

When throwing that into an `if` statement in R only the first element will be used, in this case a `FALSE`, therefore the colnames will not be assigned properly by `ds.cbind`.

It could be solved by replacing that line by `if(any(typ %in% c('data.frame', 'matrix'))){`

-----------------------------------

Aside from that, the function `ds.cbind` accepts the argument `force.colnames` (to force the column names) but it's not used on the function itself, so there is no way of manually assigning the column names directly.

**Comment by StuartWheater** [comment]
I have made the suggested changes, and reviewed other code to see if a similar problem exists.
The changes are planed to be included in 6.1.1 and following releases.
Stuart
