### ISSUE TITLE
Consistent syntax for specifying variables

### ISSUE THREAD

**Issue by andrewjamesturner0** [datashield/dsBaseClient#4]
### Syntax 1

Most functions expect variables in the form `'D$VAR'`. 
For example: 
`ds.mean('D$LAB_HDL')`
or
`ds.log('D$LAB_TSC')`
### Syntax 2

Other functions expect an explicit dataframe argument and loose variable names:
For example: 
`ds.glm(data='D', formula=LAB_HDL ~ GENDER, family='gaussian')`
or
`ds.meanByClass(x='D', outvar='LAB_TSC', covar='GENDER')`
### Is it possible to make all functions use syntax 1?

For example:
`ds.meanByClass(outvar='D$LAB_TSC', cover='D$GENDER')`
`ds.glm(formula=D$LAB_HDL ~ D$GENDER, family='gaussian')`
### Or make the dataframe an implicit argument in all functions?

For example:
`ds.mean('LAB_HDL')`
`ds.mean('LAB_HDL', data='E')`

`ds.meanByClass(outvar='LAB_TSC', covar='GENDER')`
`ds.meanByClass(outvar='LAB_TSC', covar='GENDER', data='E')`

**Comment by agaye** [comment]
This difference in syntax was deliberate to allow for the flexibility of using 'standalone' objects/variables or object/variables that are nested in other object. 
For example a user should be able to use a column/variable in a dataframe or assin that column and used is as a loose vector...as you would expect in R
Futhermore to allow for this flexibility considerable number of lines have been written within certain function so you should carefully consider changes as somemight disrupt those inner lines.


      De : Andrew Turner <notifications@github.com>
 À : datashield/dsBaseClient <dsBaseClient@noreply.github.com> 
 Envoyé le : Mardi 17 février 2015 11h08
 Objet : [dsBaseClient] Consistent syntax for specifying variables (#4)
   

Examples of different syntax

Syntax 1
Most functions expect variables in the form 'D$VAR'. 
For example: 
ds.mean('D$LAB_HDL')
or
ds.log('D$LAB_TSC')
Syntax 2
Other functions expect an explicit dataframe argument and loose variable names:
For example: 
ds.glm(data='D', formula=LAB_HDL ~ GENDER, family='gaussian')
or
ds.meanByClass(x='D', outvar='LAB_TSC', covar='GENDER')
Improvement

Is it possible to make all functions use syntax 1?
For example:
ds.meanByClass(outvar='D$LAB_TSC', cover='D$GENDER')
ds.glm(formula=LAB_HDL ~ GENDER, family='gaussian')
Or make the dataframe an implicit argument in all functions?
For example:
ds.mean('LAB_HDL')
ds.mean('LAB_HDL', data='E')ds.meanByClass(outvar='LAB_TSC', covar='GENDER')
ds.meanByClass(outvar='LAB_TSC', covar='GENDER', data='E')—

**Comment by pb51** [comment]
Functions are now more consistent but it would be a false economy to remove the flexibility to do this anyway, so leave as is
